rem https://stackoverflow.com/questions/14284269/why-doesnt-python-recognize-my-utf-8-encoded-source-file/14284404#14284404
chcp 65001
python download_snow_chmi.py
python download_snow_chmi_manualmeasure.py
python download_snow_chmi_oah.py
python download_snow_chmi_resorts.py
python download_holidayinfo.py
python download_sumavaeu.py
python download_bergfex.py
